load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "zlib",
    srcs = [
        "zlib.h",
        "zutil.h",
        "gzguts.h",
        "crc32.h",
        "deflate.h",
        "inftrees.h",
        "inflate.h",
        "inffast.h",
        "inffixed.h",
        "trees.h",
		"adler32.c",
		"compress.c",
		"crc32.c",
		"deflate.c",
		"gzclose.c",
		"gzlib.c",
		"gzread.c",
		"gzwrite.c",
		"infback.c",
		"inffast.c",
		"inflate.c",
		"inftrees.c",
		"trees.c",
		"uncompr.c",
		"zutil.c",
    ],

    visibility = ["//visibility:public"],
)

